// <auto-generated />
using System;
using EventsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventsAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231019021940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventsAPI.Models.Admission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdmissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EventListingId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EventListingId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("EventsAPI.Models.EventListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MusicId")
                        .HasColumnType("int");

                    b.Property<int?>("OutletId")
                        .HasColumnType("int");

                    b.Property<string>("PromoImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromoImage2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromoImage3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SponsorId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketOutletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.HasIndex("MusicId");

                    b.HasIndex("SponsorId");

                    b.HasIndex("TicketOutletId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventsAPI.Models.Music", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EventListingId")
                        .HasColumnType("int");

                    b.Property<string>("MusicProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventListingId");

                    b.ToTable("Musics");
                });

            modelBuilder.Entity("EventsAPI.Models.Outlet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EventListingId")
                        .HasColumnType("int");

                    b.Property<string>("OutletName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventListingId");

                    b.ToTable("Outlets");
                });

            modelBuilder.Entity("EventsAPI.Models.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EventListingId")
                        .HasColumnType("int");

                    b.Property<string>("EventSponsor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventListingId");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("EventsAPI.Models.Admission", b =>
                {
                    b.HasOne("EventsAPI.Models.EventListing", "EventListing")
                        .WithMany()
                        .HasForeignKey("EventListingId");

                    b.Navigation("EventListing");
                });

            modelBuilder.Entity("EventsAPI.Models.EventListing", b =>
                {
                    b.HasOne("EventsAPI.Models.Admission", "Admission")
                        .WithMany()
                        .HasForeignKey("AdmissionId");

                    b.HasOne("EventsAPI.Models.Music", "Music")
                        .WithMany()
                        .HasForeignKey("MusicId");

                    b.HasOne("EventsAPI.Models.Sponsor", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId");

                    b.HasOne("EventsAPI.Models.Outlet", "Outlet")
                        .WithMany()
                        .HasForeignKey("TicketOutletId");

                    b.Navigation("Admission");

                    b.Navigation("Music");

                    b.Navigation("Outlet");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("EventsAPI.Models.Music", b =>
                {
                    b.HasOne("EventsAPI.Models.EventListing", "EventListing")
                        .WithMany()
                        .HasForeignKey("EventListingId");

                    b.Navigation("EventListing");
                });

            modelBuilder.Entity("EventsAPI.Models.Outlet", b =>
                {
                    b.HasOne("EventsAPI.Models.EventListing", "EventListing")
                        .WithMany()
                        .HasForeignKey("EventListingId");

                    b.Navigation("EventListing");
                });

            modelBuilder.Entity("EventsAPI.Models.Sponsor", b =>
                {
                    b.HasOne("EventsAPI.Models.EventListing", "EventListing")
                        .WithMany()
                        .HasForeignKey("EventListingId");

                    b.Navigation("EventListing");
                });
#pragma warning restore 612, 618
        }
    }
}
